# This is a docker compose local test environment for a no replication environment setup
version: "3.9"
services:
  redis:
    image: redis:7.0.5
  
  backend:
    build: ./Backend
    depends_on:
      - redis
    ports:
      - "8080:8080"
    environment:
      MONGO_DB_USERNAME: $MONGO_DB_USERNAME
      MONGO_DB_PASSWORD: $MONGO_DB_PASSWORD
      JWT_SECRET_KEY: $JWT_SECRET_KEY
      MAIL_PASSWORD: $MAIL_PASSWORD
      GOOGLE_CLIENT_SECRET: $GOOGLE_CLIENT_SECRET
      GOOGLE_OAUTH2_CLIENT_ID: $GOOGLE_OAUTH2_CLIENT_ID
      ENVIRONMENT: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CORS_ALLOWED_ORIGIN: http://localhost # NOTE (KARIM) : Use the public domain name of the site
    volumes:
      - backend_logs:/ticp/The-Internet-Chkpt
  
  frontend:
    build: ./Frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    environment:
      SERVER_LOCATION: http://backend:8080
      OAUTH2_PROXY : http://localhost:8080
volumes:
  backend_logs:
