version: "3.9" # optional since v1.27.0
services:
  ticp_back:
    build:
      context: ./Backend/
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      MONGO_DB_USERNAME: $MONGO_DB_USERNAME
      MONGO_DB_PASSWORD: $MONGO_DB_PASSWORD
      JWT_SECRET_KEY: $JWT_SECRET_KEY
      MAIL_PASSWORD: $MAIL_PASSWORD
      GOOGLE_CLIENT_SECRET: $GOOGLE_CLIENT_SECRET
      GOOGLE_OAUTH2_CLIENT_ID: $GOOGLE_OAUTH2_CLIENT_ID
      ENVIRONMENT: development
    networks:
      - back-network
  ticp_front:
    build:
      context: ./Frontend/
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - front-network
      - back-network
networks:
  front-network: {}
  back-network: {}
