server:
  port: 8080

# NOTE : <username> and <pwd> must be changed by the developer when working with the db, only authorized accounts can be used
# NOTE : the database and account must be switched to production when deploying to the production cluster
spring:
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@ticp-cluster0.dk5t9.mongodb.net/${ENVIRONMENT}
      database: development
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: the.internet.checkpoint.team@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET_KEY}