server:
  port: 8080

# NOTE : <username> and <pwd> must be changed by the developer when working with the db, only authorized accounts can be used
# NOTE : the database and account must be switched to production when deploying to the production cluster
spring:
  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@c0.tec6qnx.mongodb.net/${ENVIRONMENT}
      database: ${ENVIRONMENT}
      auto-index-creation: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_OAUTH2_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: the.internet.checkpoint.team@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET_KEY}
authorizedRedirectUrls: http://localhost/oauth2/redirect, http://localhost:8080/oauth2/callback/google, http://localhost:3000/oauth2/redirect,http://localhost:3000/checkpoints
ticp:
  configs:
    date_format: "yyyy.MM.dd 'at' HH:mm:ss"
    allowed-origin: http://localhost:3000