server:
  port: 8081

# NOTE : <username> and <pwd> must be changed by the developer when working with the db, only authorized accounts can be used
# NOTE : the database and account must be switched to production when deploying to the production cluster
spring:
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@ticp-cluster0.dk5t9.mongodb.net/development
      database: development
ticp:
  configs:
    date_format: "yyyy.MM.dd 'at' HH:mm:ss"
